language: go
go:
  - 1.13.x

install:
  - go get github.com/onsi/ginkgo/ginkgo
  - go mod tidy
  - export PATH=$PATH:$HOME/gopath/bin

script:
  - ginkgo -r --randomizeAllSpecs --randomizeSuites --race --trace