// Code generated by MockGen. DO NOT EDIT.
// Source: cosmos-go-sdk/rest (interfaces: IResource)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockIResource is a mock of IResource interface
type MockIResource struct {
	ctrl     *gomock.Controller
	recorder *MockIResourceMockRecorder
}

// MockIResourceMockRecorder is the mock recorder for MockIResource
type MockIResourceMockRecorder struct {
	mock *MockIResource
}

// NewMockIResource creates a new mock instance
func NewMockIResource(ctrl *gomock.Controller) *MockIResource {
	mock := &MockIResource{ctrl: ctrl}
	mock.recorder = &MockIResourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIResource) EXPECT() *MockIResourceMockRecorder {
	return m.recorder
}

// BuildURI mocks base method
func (m *MockIResource) BuildURI() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildURI")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildURI indicates an expected call of BuildURI
func (mr *MockIResourceMockRecorder) BuildURI() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildURI", reflect.TypeOf((*MockIResource)(nil).BuildURI))
}

// Key mocks base method
func (m *MockIResource) Key() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Key")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Key indicates an expected call of Key
func (mr *MockIResourceMockRecorder) Key() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Key", reflect.TypeOf((*MockIResource)(nil).Key))
}

// ResourcePath mocks base method
func (m *MockIResource) ResourcePath() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResourcePath")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResourcePath indicates an expected call of ResourcePath
func (mr *MockIResourceMockRecorder) ResourcePath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResourcePath", reflect.TypeOf((*MockIResource)(nil).ResourcePath))
}

// ResourceType mocks base method
func (m *MockIResource) ResourceType() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResourceType")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResourceType indicates an expected call of ResourceType
func (mr *MockIResourceMockRecorder) ResourceType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResourceType", reflect.TypeOf((*MockIResource)(nil).ResourceType))
}
